
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import java.util.TreeSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sebastián
 */
public class gui_main extends javax.swing.JFrame {

    /**
     * Creates new form gui_main
     */
    Control miControl = new Control();
    Operaciones ops = new Operaciones();
    int cont;
    Set<Desarrollador> unSet; 
    Set<Desarrollador> unSetWeb; 
    Set<Desarrollador> unSetJava; 
    public gui_main() {
        initComponents();
        jPanel3.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        implementacion = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbn_hashset = new javax.swing.JRadioButton();
        rbn_treeset = new javax.swing.JRadioButton();
        rbn_linkedhashset = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        chb_web = new javax.swing.JCheckBox();
        chb_java = new javax.swing.JCheckBox();
        chb_celulares = new javax.swing.JCheckBox();
        btn_agregar = new javax.swing.JButton();
        btn_reporte = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Implementacion"));

        jLabel5.setText("Seleccione que tipo de Set quiere usar");

        buttonGroup1.add(rbn_hashset);
        rbn_hashset.setSelected(true);
        rbn_hashset.setText("HashSet");

        buttonGroup1.add(rbn_treeset);
        rbn_treeset.setText("TreeSet");

        buttonGroup1.add(rbn_linkedhashset);
        rbn_linkedhashset.setText("LinkedHashSet");

        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbn_hashset)
                .addGap(18, 18, 18)
                .addComponent(rbn_treeset)
                .addGap(18, 18, 18)
                .addComponent(rbn_linkedhashset)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbn_hashset)
                    .addComponent(rbn_treeset)
                    .addComponent(rbn_linkedhashset))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setName("panel2"); // NOI18N

        jLabel1.setText("A continuacion ingrese los datos de sus desarroladores y presione el boton agregar para ");

        jLabel4.setText("añadirlo. Luego presione el botón Reporte para ver toda la informacion ingresada.");

        jLabel3.setText("Nombre del desarrollador:");

        jLabel2.setText("Tipo de desarrollador:");

        chb_web.setText("Web");

        chb_java.setText("Java");

        chb_celulares.setText("Celulares");

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_reporte.setText("Reporte");
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btn_agregar)
                                    .addGap(26, 26, 26)
                                    .addComponent(btn_reporte))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(292, 292, 292)
                                    .addComponent(btn_salir)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chb_web, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chb_java)
                                    .addComponent(chb_celulares)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(chb_web))
                .addGap(3, 3, 3)
                .addComponent(chb_java)
                .addGap(3, 3, 3)
                .addComponent(chb_celulares)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregar)
                    .addComponent(btn_reporte))
                .addGap(6, 6, 6)
                .addComponent(btn_salir)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // código del boton agregar{
            if( txt_nombre.getText().equals("")){
                cont=cont + 1; 
            }
            if(chb_web.isSelected() == false && chb_java.isSelected()==false && chb_celulares.isSelected()==false){
                cont=cont + 2;  
            }
        
        if(cont==3){
            JOptionPane.showMessageDialog(null, "Porfavor ingrese un nombre y seleccione un tipo de desarrolador", "Advertencia", JOptionPane.ERROR_MESSAGE);
            cont=0;
        }else{
            if(cont==2){
                JOptionPane.showMessageDialog(null, "Porfavor seleccione un tipo de desarrolador", "Advertencia", JOptionPane.ERROR_MESSAGE);
                cont=0;
            }else{
                if(cont==1){
                    JOptionPane.showMessageDialog(null, "Porfavor ingrese un nombre", "Advertencia", JOptionPane.ERROR_MESSAGE);
                    cont=0;
                }else{
                    //miControl.agregar(chb_web.isSelected(),chb_java.isSelected(), chb_celulares.isSelected() , txt_nombre.getText());
                    
                    Desarrollador des = new Desarrollador(txt_nombre.getText(), chb_java.isSelected(), chb_web.isSelected(),chb_celulares.isSelected() );
                     unSet.add(des);
                    
                    chb_web.setSelected(false);
                    chb_java.setSelected(false);
                    chb_celulares.setSelected(false);
                    txt_nombre.setText("");
                }
            }
        }
       
        
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed
        // código del boton reporte
        //JOptionPane.showMessageDialog(null,miControl.reporte());
        JOptionPane.showMessageDialog(null, ops.javawebcelular(unSet));
        JOptionPane.showMessageDialog(null, ops.javanotweb(unSet));
        JOptionPane.showMessageDialog(null, ops.webcelularnotjava(unSet));
        JOptionPane.showMessageDialog(null, ops.weborcelularnotjava(unSet));
        ArrayList<String> al = new ArrayList();
        al = ops.masgrande(unSet);
        Iterator it = al.iterator();
        String resultado = "";
        while (it.hasNext()){
            resultado=resultado+it.next()+", ";
        }
        JOptionPane.showMessageDialog(null, "El mas grande es: "+resultado);
       
        //******************************* verificar si es subconjunto
        ArrayList<Desarrollador> javadevs = new ArrayList<Desarrollador>();
        ArrayList<Desarrollador> webdevs = new ArrayList<Desarrollador>();
                for (Desarrollador dev : unSet){
                    if (dev.isJavaDeveloper()) 
                    {
                        javadevs.add(dev);
                    }
                    if (dev.isWebDeveloper()) 
                    {
                        webdevs.add(dev);
                    }
                }
       JOptionPane.showMessageDialog(null, ops.isSubconjunto(javadevs, webdevs));
        //******************************
    }//GEN-LAST:event_btn_reporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel3.setVisible(true);
        jPanel2.setVisible(false);
        
        if(rbn_hashset.isSelected()){
            String imp="HashSet";
            unSet = miControl.creacion(imp);
            unSetWeb=miControl.creacion(imp);
            unSetJava=miControl.creacion(imp);
            //siguiente.setVisible(true);
            //this.setVisible(false);
        }else if(rbn_treeset.isSelected()){
            String imp="TreeSet";
            unSet = miControl.creacion(imp);
            unSetWeb=miControl.creacion(imp);
            unSetJava=miControl.creacion(imp);
            //lamando a la siguiente ventana
            //siguiente.setVisible(true);
            //this.setVisible(false);
        }else if(rbn_linkedhashset.isSelected()){
            String imp="LinkedHashSet";
            //Llamando al método que crea el tipo de Set dependiendo de la implementacion seleccionada
            unSet = miControl.creacion(imp);
            unSetWeb=miControl.creacion(imp);
            unSetJava=miControl.creacion(imp);
            //Llamando a la siguiente ventana
            //siguiente.setVisible(true);
            //this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Porfavor seleccione un tipo de implementacion.", "Advertencia", JOptionPane.ERROR_MESSAGE );
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_reporte;
    private javax.swing.JButton btn_salir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chb_celulares;
    private javax.swing.JCheckBox chb_java;
    private javax.swing.JCheckBox chb_web;
    public static javax.swing.ButtonGroup implementacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton rbn_hashset;
    private javax.swing.JRadioButton rbn_linkedhashset;
    private javax.swing.JRadioButton rbn_treeset;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
